apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: "borodindmitriy/e-commerce-back:{{ .Values.gitSha }}"
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrete_id }}
                  key: JWT_SECRET_KEY
            - name: DB_URL
              value: mongodb://mongodb-cluster-ip-service:27017
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrete_id }}
                  key: DB_NAME
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "10000"
            - name: WS_HOST
              value: "0.0.0.0"
            - name: WS_PORT
              value: "10001"
            - name: NODE_ENV
              value: "development"
          ports:
            - containerPort: 10000
            - containerPort: 10001
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "256m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
