steps:
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  # This steps builds the container image for front-end and back-end.
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildFrontEnd
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
      - '-f'
      - './packages/frontend/Dockerfile.dev'
      - './packages/frontend'
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildBackEnd
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'
      - '-f'
      - './packages/backend/Dockerfile.dev'
      - './packages/backend'

  # This steps run the fmt, lint, test, build  for front-end.
  - name: 'gcr.io/cloud-builders/docker'
    id: RunFmtFrontEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'fmt'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunLintFrontEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'lint'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunTestFrontEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'test'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunBuildFrontEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'build'

  # This steps run the fmt, lint, test, build for back-end.
  - name: 'gcr.io/cloud-builders/docker'
    id: RunFmtBackEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'fmt'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunLintBackEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'lint'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunTestBackEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'test'
  - name: 'gcr.io/cloud-builders/docker'
    id: RunBuildBackEnd
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'
      - 'npm'
      - 'run'
      - 'build'

  # This step pushes the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: PushFrontEnd
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/e-commerce-front:$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    id: PushBackEnd
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/e-commerce-back:$SHORT_SHA'