version: "3.7"
services:
  frontend:
    restart: always
    build: 
      context: "./packages/frontend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - ishop-network
    environment:
      SERVER_NAME: ishop.ru
      SERVER_HOST: backend
      SERVER_PORT: 10000
      WS_HOST: backend
      WS_PORT: 10001

  backend:
    restart: "always"
    build: 
      context: "./packages/backend"
      dockerfile: "Dockerfile.dev"
    volumes:
      - /app/node_modules
      - ./:/app
      - ./uploadedFiles:/app/uploadedFiles
    environment:
      JWT_SECRET_KEY: xtoLhZqKfmXU2MVjHuu74AvYUeBsswsWFXxzsbNJ4U3iinJjGs9RAxmzcrU3UrHR
      DB_URL: mongodb://mongoDB:27017
      DB: example-db-name
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 10000
      WS_HOST: 0.0.0.0
      WS_PORT: 10001
    depends_on:
      - mongoDB
    networks:
      - ishop-network

  mongoDB:
    restart: "always"
    image: mongo:4.2.3
    ports:
      - "127.0.0.1:27021:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - ishop-network

networks:
  ishop-network:
