apiVersion: skaffold/v2beta8
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: borodindmitriy/e-commerce-front
      context: packages/frontend
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: "**/*"
            dest: "build"
deploy: 
  kubectl:
    manifests: 
      - k8s/client-deployment.yaml