version: "3"
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - "127.0.0.1:1337:1337"
    expose:
      - "1337"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: strapi
      PGADMIN_DEFAULT_PASSWORD: strapi
    links:
      - "postgres:postgres"
    ports:
      - "127.0.0.1:1338:80"
    expose:
      - "1338"
