apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: borodindmitriy/e-commerce-back
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: data-base
                  key: JWT_SECRET_KEY
            - name: DB_URL
              value: mongodb://mongodb-cluster-ip-service:27017
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: data-base
                  key: DB_NAME
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: '10000'
            - name: WS_HOST
              value: "0.0.0.0"
            - name: WS_PORT
              value: '10001'
            - name: NODE_ENV
              value: 'development'
          ports:
            - containerPort: 10000
            - containerPort: 10001
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"


