name: CI
on: [push]
jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm install --frozen-lockfile
        env:
          CI: true

      - name: Bootstrap
        run: npm run bootstrap
        env:
          CI: true

      - name: Prettier
        run: npm run fmt
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Build front-end image
        run: docker build -t borodindmitriy/e-commerce-front -f ./packages/frontend/Dockerfile.dev ./packages/frontend

      - name: Build back-end image
        run: docker build -t borodindmitriy/e-commerce-back -f ./packages/backend/Dockerfile.dev ./packages/backend

      - name: Build code for front-end
        run: docker run borodindmitriy/e-commerce-front npm run build

      - name: Build code for back-end
        run: docker run borodindmitriy/e-commerce-back npm run build
